name: db_update_check

on:
  workflow_dispatch: {}
  # Run every day at 5AM UTC
  schedule:
    - cron: '0 5 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Clair V4 update
        uses: quay/clair-action@main
        with:
          db-file: matcher.db
          mode: update
