---
name: Fast Forward
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]
jobs:
  fast-forward:
    uses: quay/clair-workflows/.github/workflows/fast-forward.yml@main

    permissions:
      contents: write
      pull-requests: write
      issues: write
